#!/usr/bin/env bash
#
# collect-apple-env.sh — gather every Apple-side variable the server needs
# (APNs push + StoreKit IAP verification) and emit them in two buckets:
#
#   • non-secret config  -> deploy/apple.env   (merge into server.env, or push as
#                            GitHub *variables*)
#   • the APNs .p8 key    -> deploy/secrets/apns_key_p8   (a real secret)
#
# It then prints ready-to-run `gh` commands so GitHub stays the single source of
# truth (see infra/deploy/agent/set-host-secrets.sh).
#
# Usage:
#   deploy/scripts/collect-apple-env.sh                # interactive
#   APNS_KEY_ID=… APNS_TEAM_ID=… APNS_P8_PATH=… \
#     STOREKIT_BUNDLE_ID=… … deploy/scripts/collect-apple-env.sh --non-interactive
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
APPLE_ENV="$ROOT/deploy/apple.env"
SECRETS_DIR="$ROOT/deploy/secrets"
P8_OUT="$SECRETS_DIR/apns_key_p8"
NONINTERACTIVE="${1:-}"

ask() { # ask VAR "Prompt" "default"
  local var="$1" prompt="$2" def="${3:-}" cur="${!1:-}" val
  if [[ "$NONINTERACTIVE" == "--non-interactive" ]]; then
    printf -v "$var" '%s' "${cur:-$def}"; return
  fi
  read -r -p "$prompt${def:+ [$def]}: " val || true
  printf -v "$var" '%s' "${val:-${cur:-$def}}"
}

echo "── Apple push (APNs) ─────────────────────────────────────────────"
ask APNS_KEY_ID    "APNs Key ID (Apple Developer → Keys)"      "${APNS_KEY_ID:-}"
ask APNS_TEAM_ID   "Apple Team ID"                             "${APNS_TEAM_ID:-}"
ask APNS_P8_PATH   "Path to the APNs .p8 key file"             "${APNS_P8_PATH:-}"
ask APNS_TOPIC_IOS "iOS bundle id (APNs topic)"                "${APNS_TOPIC_IOS:-martin.rougeron.DissQus-iOS}"
ask APNS_TOPIC_MACOS "macOS bundle id (APNs topic)"            "${APNS_TOPIC_MACOS:-martin.rougeron.DissQus}"
ask APNS_ENV       "APNs env (sandbox|production)"             "${APNS_ENV:-production}"

echo "── StoreKit (iOS in-app purchase verification) ──────────────────"
ask STOREKIT_BUNDLE_ID     "App bundle id"                     "${STOREKIT_BUNDLE_ID:-martin.rougeron.DissQus-iOS}"
ask STOREKIT_PRODUCT_ID    "Subscription product id"           "${STOREKIT_PRODUCT_ID:-com.example.app.premium.monthly}"
ask STOREKIT_ENV           "StoreKit env (Production|Sandbox)" "${STOREKIT_ENV:-Production}"
ask STOREKIT_APP_APPLE_ID  "Numeric App Store app id"          "${STOREKIT_APP_APPLE_ID:-}"
ask STOREKIT_ROOT_CERTS_DIR "Apple root certs dir (in container)" "${STOREKIT_ROOT_CERTS_DIR:-/certs}"

# --- Write the secret .p8 ---------------------------------------------------
if [[ -n "${APNS_P8_PATH:-}" ]]; then
  [[ -f "$APNS_P8_PATH" ]] || { echo "❌ .p8 not found: $APNS_P8_PATH" >&2; exit 1; }
  grep -q "BEGIN PRIVATE KEY" "$APNS_P8_PATH" || { echo "❌ $APNS_P8_PATH is not a PEM private key" >&2; exit 1; }
  mkdir -p "$SECRETS_DIR"; chmod 700 "$SECRETS_DIR"
  cp "$APNS_P8_PATH" "$P8_OUT"; chmod 600 "$P8_OUT"
  echo "✅ APNs key → $P8_OUT (secret; gitignored)"
fi

# --- Write the non-secret config fragment -----------------------------------
cat > "$APPLE_ENV" <<EOF
# Generated by deploy/scripts/collect-apple-env.sh — NON-SECRET Apple config.
# Merge into deploy/server.env, or push as GitHub repo/environment *variables*.
# The APNs .p8 itself is the only secret and lives in deploy/secrets/apns_key_p8.
APNS_KEY_ID=$APNS_KEY_ID
APNS_TEAM_ID=$APNS_TEAM_ID
APNS_TOPIC_IOS=$APNS_TOPIC_IOS
APNS_TOPIC_MACOS=$APNS_TOPIC_MACOS
APNS_ENV=$APNS_ENV
STOREKIT_BUNDLE_ID=$STOREKIT_BUNDLE_ID
STOREKIT_PRODUCT_ID=$STOREKIT_PRODUCT_ID
STOREKIT_ENV=$STOREKIT_ENV
STOREKIT_APP_APPLE_ID=$STOREKIT_APP_APPLE_ID
STOREKIT_ROOT_CERTS_DIR=$STOREKIT_ROOT_CERTS_DIR
EOF
echo "✅ non-secret Apple config → $APPLE_ENV"

cat <<EOF

Next — push to GitHub so it stays the source of truth (set ENV=production|preprod):
  ENV=production
  gh secret   set APNS_KEY_P8 --env "\$ENV" < "$P8_OUT"
$(while IFS='=' read -r k v; do [[ "$k" == \#* || -z "$k" ]] && continue; echo "  gh variable set $k --env \"\$ENV\" --body '$v'"; done < "$APPLE_ENV")

Then copy these into /etc/hqcat/<stack>/server.env on the host that runs the stack.
EOF
